export {default as Private} from './Private'
export {default as PriceShipping} from './PriceShipping'
export {default as Management} from './Management'
export {default as Reports} from './Reports'
export {default as Order} from './Order'
export {default as Home} from './Home'